In [4]:
import torch

In [30]:
a = torch.arange(9).reshape(1,3,-1)
print(a)
b = torch.zeros(1,3,3, dtype=bool)
print(b)
c = torch.tensor([[0,1,2]])
print(c)
c = c.unsqueeze(-1)
c_2 = torch.tensor([[0,1,2]])

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]]])
tensor([[0, 1, 2]])


In [31]:
e = torch.zeros(1,3,3, dtype=bool)
e_1 = e.scatter(-1, c, True)
print(e_1)

e_2 = e.scatter(-1, c_2, True)
print(e_2)

tensor([[[ True, False, False],
         [False,  True, False],
         [False, False,  True]]])


RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [33]:
a.gather(-1, c)

tensor([[[0],
         [4],
         [8]]])

In [2]:
x = 1
match x:
    case 0 | 1:
        print('hit')
    case _:
        print('miss')
    # end
# end


hit


In [ ]:
torch.randint(20, 40, (2, 3), device=x.device)

tensor([[30, 22, 34],
        [24, 31, 20]])

In [30]:
a = torch.tensor([[True, True, False],[False, True, True]],dtype=torch.bool)
print(a.shape)
_, idx_unshaped = torch.where(a)
idx = idx_unshaped.reshape(2,-1)
print(idx)

torch.Size([2, 3])
tensor([[0, 1],
        [1, 2]])


In [ ]:
a = torch.tensor([True, True, False],dtype=torch.bool)
idx_a = torch.where(a)
print(idx_a)

(tensor([0, 1]),)


In [37]:
a = torch.tensor([[True, True, False],[False, True, True]],dtype=torch.bool)
# a = torch.tensor([True, True, False],dtype=torch.bool)
print(a.nonzero(as_tuple=True)[0])

tensor([0, 0, 1, 1])


In [43]:
a = torch.arange(6).reshape(2,3)

In [ ]:
remasking = None
x0_p_current = None
nums_transfer_tokens = None
mask_transfered = None
batchid = None
x0 = None
mask_current_full = None
step_per_block = None

k = nums_transfer_tokens[:, step_per_block]

if remasking == 'random':
    idx_mask_current = mask_current_full[0].nonzero(as_tuple=True)[0] # 1d
    idx_unmask_k = torch.randint(
        idx_mask_current[0], idx_mask_current[-1],
        (mask_current_full.shape[0], k)
    )
else:
    _, idx_unmask_k = torch.topk(x0_p_current, k=nums_transfer_tokens[:, step_per_block])
# end if-else

mask_transfered[idx_unmask_k] = True
x[mask_transfered] = x0[mask_transfered]