In [2]:
import torch

In [30]:
a = torch.arange(9).reshape(1,3,-1)
print(a)
b = torch.zeros(1,3,3, dtype=bool)
print(b)
c = torch.tensor([[0,1,2]])
print(c)
c = c.unsqueeze(-1)
c_2 = torch.tensor([[0,1,2]])

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]]])
tensor([[0, 1, 2]])


In [31]:
e = torch.zeros(1,3,3, dtype=bool)
e_1 = e.scatter(-1, c, True)
print(e_1)

e_2 = e.scatter(-1, c_2, True)
print(e_2)

tensor([[[ True, False, False],
         [False,  True, False],
         [False, False,  True]]])


RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [33]:
a.gather(-1, c)

tensor([[[0],
         [4],
         [8]]])

In [2]:
x = 1
match x:
    case 0 | 1:
        print('hit')
    case _:
        print('miss')
    # end
# end


hit


In [ ]:
torch.randint(20, 40, (2, 3), device=x.device)

tensor([[30, 22, 34],
        [24, 31, 20]])

In [30]:
a = torch.tensor([[True, True, False],[False, True, True]],dtype=torch.bool)
print(a.shape)
_, idx_unshaped = torch.where(a)
idx = idx_unshaped.reshape(2,-1)
print(idx)

torch.Size([2, 3])
tensor([[0, 1],
        [1, 2]])


In [ ]:
a = torch.tensor([True, True, False],dtype=torch.bool)
idx_a = torch.where(a)
print(idx_a)

(tensor([0, 1]),)


In [37]:
a = torch.tensor([[True, True, False],[False, True, True]],dtype=torch.bool)
# a = torch.tensor([True, True, False],dtype=torch.bool)
print(a.nonzero(as_tuple=True)[0])

tensor([0, 0, 1, 1])


In [43]:
a = torch.arange(6).reshape(2,3)

In [ ]:
remasking = None
x0_p_current = None
nums_transfer_tokens = None
mask_transfered = None
batchid = None
x0 = None
mask_current_full = None
step_per_block = None

k = nums_transfer_tokens[:, step_per_block]

if remasking == 'random':
    idx_mask_current = mask_current_full[0].nonzero(as_tuple=True)[0] # 1d
    idx_unmask_k = torch.randint(
        idx_mask_current[0], idx_mask_current[-1],
        (mask_current_full.shape[0], k)
    )
else:
    _, idx_unmask_k = torch.topk(x0_p_current, k=nums_transfer_tokens[:, step_per_block])
# end if-else

mask_transfered[idx_unmask_k] = True
x[mask_transfered] = x0[mask_transfered]

In [45]:
torch.full(a.shape, 1)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [46]:
import torch

In [65]:
a = torch.arange(6).reshape(2,3)
a.shape

torch.Size([2, 3])

In [66]:
b = torch.tensor([[2],[1]])
b.shape

torch.Size([2, 1])

In [68]:
# a.scatter_(1, b.to(torch.long), 0)
a.scatter_(1, b, 0)

tensor([[0, 1, 0],
        [3, 0, 5]])

In [11]:
a = torch.arange(6).reshape(2,3)
b = torch.arange(6,12).reshape(2,3)

In [12]:
mask = torch.full(a.shape, False)

In [13]:
idx = torch.tensor([[2],[1]],dtype=torch.long)

In [ ]:
mask.scatter_(-1, idx, True)

tensor([[False, False,  True],
        [False,  True, False]])

In [22]:
a_ = a[mask].reshape(2,-1)

In [26]:
torch.exp(a_.to(torch.bfloat16).mean(dim=-1))

tensor([ 7.3750, 54.5000], dtype=torch.bfloat16)

In [81]:
print(a)
a[mask] = b[mask]
print(a)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  1,  8],
        [ 3, 10,  5]])


In [2]:
[i for i in range(1)]

[0]

In [ ]:
a = torch.tensor([[10]], dtype=torch.float)
b = torch.tensor([[100]], dtype=torch.float)
print(a/b)

tensor([[0.1000]])


In [4]:
print(torch.arange(6).reshape(2,3))
torch.where(torch.arange(6).reshape(2,3) % 2 == 0)

tensor([[0, 1, 2],
        [3, 4, 5]])


(tensor([0, 0, 1]), tensor([0, 2, 1]))

In [6]:
torch.tensor([1,0,1], dtype=torch.bool).nonzero(as_tuple=True)

(tensor([0, 2]),)

In [2]:
x = torch.tensor([[10, 20, 30, 40],[1,2,3,4]], device="cuda")
perm = torch.randperm(x.numel(), device=x.device)
perm

tensor([3, 1, 6, 4, 0, 2, 5, 7], device='cuda:0')

In [14]:
a = torch.tensor([[1,0,1,1],[0,1,1,1]], dtype=bool, device='cuda:0')
mask_current_full = a

In [26]:
idx_mask_current = mask_current_full.nonzero(as_tuple=True)[-1].reshape(mask_current_full.shape[0], -1) # 1d
perm = torch.argsort(torch.rand(idx_mask_current.shape[0], idx_mask_current.shape[1], device=mask_current_full.device), dim=-1)
idx_unmask_k = idx_mask_current.gather(-1, perm)
print(idx_unmask_k)
print(idx_unmask_k[:,:2])

tensor([[2, 3, 0],
        [2, 1, 3]], device='cuda:0')
tensor([[2, 3],
        [2, 1]], device='cuda:0')


In [3]:
torch.topk

<function torch._VariableFunctionsClass.topk>