In [1]:
import torch

In [30]:
a = torch.arange(9).reshape(1,3,-1)
print(a)
b = torch.zeros(1,3,3, dtype=bool)
print(b)
c = torch.tensor([[0,1,2]])
print(c)
c = c.unsqueeze(-1)
c_2 = torch.tensor([[0,1,2]])

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]]])
tensor([[0, 1, 2]])


In [31]:
e = torch.zeros(1,3,3, dtype=bool)
e_1 = e.scatter(-1, c, True)
print(e_1)

e_2 = e.scatter(-1, c_2, True)
print(e_2)

tensor([[[ True, False, False],
         [False,  True, False],
         [False, False,  True]]])


RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [33]:
a.gather(-1, c)

tensor([[[0],
         [4],
         [8]]])