In [7]:
import torch

a = torch.arange(12).reshape(1,3,4)
b = torch.arange(12,16).reshape(1,1,4)
print(a,b)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]) tensor([[[12, 13, 14, 15]]])


In [ ]:
idx_1d = torch.tensor([1], dtype=torch.long)
idx_3d = idx_1d.view(1,1,1).expand(1,1,4)
print(idx_3d)


In [18]:
torch.gather(a, 1, idx_3d)

tensor([[[4, 5, 6, 7]]])

In [19]:
torch.scatter(a,1 ,idx_3d, b)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15],
         [ 8,  9, 10, 11]]])