In [11]:
import torch

a = torch.arange(12).reshape(1,3,4)
b = torch.arange(12,16).reshape(1,1,4)
print(a,b)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]) tensor([[[12, 13, 14, 15]]])


In [12]:
idx_1d = torch.tensor([1], dtype=torch.long)
idx_3d = idx_1d.view(1,1,1).expand(1,1,4)
print(idx_3d)


tensor([[[1, 1, 1, 1]]])


In [13]:
a.gather(1, idx_3d)

tensor([[[4, 5, 6, 7]]])

In [14]:
a.scatter(1 ,idx_3d, b)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15],
         [ 8,  9, 10, 11]]])

In [15]:
print(a)
a[:, [1], :] = b
print(a)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15],
         [ 8,  9, 10, 11]]])
