In [1]:
import inspect

def hello(*args, **kwargs):
    for k, v in kwargs.items():
        hello2(**{k: v})
    # end
# end

def hello2(*args, **kwargs):
    print(kwargs)
# end

hello(name='john')

{'name': 'john'}


In [2]:
import torch
LEN_PROMPT = 1
LEN_RESPONSE = 2
a = lambda x, len_prompt, len_response: x[(torch.arange(1, len_prompt + len_response + 1) > len_response).view(1,-1,1).expand(x.shape[0],-1,x.shape[-1])].reshape(x.shape[0], -1, x.shape[-1])
x = torch.arange(24).reshape(2,3,4)

print(x)
print((torch.arange(1, LEN_PROMPT + LEN_RESPONSE + 1) > LEN_RESPONSE).view(1,-1,1).expand(x.shape[0],-1,x.shape[-1]))
print(a(x, LEN_PROMPT, LEN_RESPONSE))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[False, False, False, False],
         [False, False, False, False],
         [ True,  True,  True,  True]],

        [[False, False, False, False],
         [False, False, False, False],
         [ True,  True,  True,  True]]])
tensor([[[ 8,  9, 10, 11]],

        [[20, 21, 22, 23]]])


In [3]:
def hello3(*args, **kwargs):
    return [i for i in args]
# end

name = 1
print(hello3(name)[0])

1


In [4]:
get_pro = lambda x, len_prompt, len_response: x[(torch.arange(1, len_prompt + len_response + 1) < len_response).view(1,-1,1).expand(x.shape[0],-1,x.shape[-1])].reshape(x.shape[0], -1, x.shape[-1])
get_res = lambda x, len_prompt, len_response: x[(torch.arange(1, len_prompt + len_response + 1) >= len_response).view(1,-1,1).expand(x.shape[0],-1,x.shape[-1])].reshape(x.shape[0], -1, x.shape[-1])

In [10]:
get_res(torch.arange(12).reshape(1,3,4),1,2)

tensor([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [9]:
def hello(*args, **kwargs):
    return args
# end

print(hello(1, name=3))


(1,)


In [7]:
def hello(*args, **kwargs):
    return tuple(arg for arg in args)
# end

a = hello(1, name=2)
print(a)


(1,)


In [ ]:
import inspect
frame = inspect.currentframe().f_locals.get('self', None)

In [ ]:
import inspect
from abc import ABC

class NONO(ABC):
    pass

class Inspector(NONO):
    def check(self):
        frame = inspect.currentframe()

        while type(frame.f_locals.get('self')).__bases__[0] == Inspector: 
            frame = frame.f_back
        # end

        return frame.f_locals.get('self').name
    # end
# end

class A(Inspector):
    def hello(self):
        return self.check()
    # end

    def hello2(self):
        return self.hello()
    # end
# end

class Client:
    def main(self):
        a = A()
        self.name = 'hello'
        print(a.hello2())
    # end
# end

Client().main()


hello


In [53]:
frame = inspect.currentframe()
print(frame)

<frame at 0x78a0e49697a0, file '/tmp/ipykernel_169150/1574227092.py', line 1, code <module>>
